// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGYKKEZ9Uwu2U8WkNdzc82vj-bPiSM4QY',
    appId: '1:362322316768:web:37d758fe09816766f32f85',
    messagingSenderId: '362322316768',
    projectId: 'barang-fe68f',
    authDomain: 'barang-fe68f.firebaseapp.com',
    databaseURL: 'https://barang-fe68f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'barang-fe68f.firebasestorage.app',
    measurementId: 'G-WJEQS2B5NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9pWg6gSrabS1F5q10DOo8u59j4BrmC6k',
    appId: '1:362322316768:android:d5b93e9a96b5c56cf32f85',
    messagingSenderId: '362322316768',
    projectId: 'barang-fe68f',
    databaseURL: 'https://barang-fe68f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'barang-fe68f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNCmgxfPQKbhL-E4uITReqFtvb4JmuE1c',
    appId: '1:362322316768:ios:c0fee4cd4adaf81bf32f85',
    messagingSenderId: '362322316768',
    projectId: 'barang-fe68f',
    databaseURL: 'https://barang-fe68f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'barang-fe68f.firebasestorage.app',
    iosBundleId: 'com.example.appMobileBarang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNCmgxfPQKbhL-E4uITReqFtvb4JmuE1c',
    appId: '1:362322316768:ios:c0fee4cd4adaf81bf32f85',
    messagingSenderId: '362322316768',
    projectId: 'barang-fe68f',
    databaseURL: 'https://barang-fe68f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'barang-fe68f.firebasestorage.app',
    iosBundleId: 'com.example.appMobileBarang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGYKKEZ9Uwu2U8WkNdzc82vj-bPiSM4QY',
    appId: '1:362322316768:web:2be47b907126e39cf32f85',
    messagingSenderId: '362322316768',
    projectId: 'barang-fe68f',
    authDomain: 'barang-fe68f.firebaseapp.com',
    databaseURL: 'https://barang-fe68f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'barang-fe68f.firebasestorage.app',
    measurementId: 'G-B0R0VQHGN3',
  );

}